title: Welcome to Braintree Support
description: >
  Documentation, Support and Resources for DocuVault Sharepoint Integrator
theme: jekyll-theme-cayman
show_downloads: true
github:
  is_project_page: false
remote_theme: Braintree-by-Vox/Braintree-theme